import numpy as np
import matplotlib.pyplot as plt

def plot_activation_functions(neuron_type):
    """
    Load the text file generated by the Haskell documentation
    script and use it to generate a png of the activation function.
    """
    x = np.arange(-10.,10.01,0.01)
    y = np.loadtxt(neuron_type + ".txt")
    title = neuron_type.title()

    if len(neuron_type.split("_")) == 2:
        split = neuron_type.split("_")
        title = split[0].title() + " of " + split[1].title()

    plt.figure()
    plt.title(title + " Neuron Activation Graph")
    plt.plot(x, y)
    plt.savefig(neuron_type + ".png")

def main():
    # Iterate through the activation functions and their derivatives
    types = [
        "sigmoid", "reclu", "tanh",
        "derivative_sigmoid", "derivative_reclu", "derivative_tanh"
    ]

    for activation in types:
        plot_activation_functions(activation)

if __name__ == '__main__':
    main()
