import numpy as np
import matplotlib.pyplot as plt

def plot_activation_functions(neuron_type):
    """
    Load the text file generated by the Haskell documentation
    script and use it to generate a png of the activation function.
    """
    x = np.arange(-10.,10.01,0.01)
    y = np.loadtxt(neuron_type + ".txt")
    title = neuron_type.title()

    if len(neuron_type.split("_")) == 2:
        split = neuron_type.split("_")
        title = split[0].title() + " of " + split[1].title()

    plt.figure()
    plt.title(title + " Neuron Activation Graph")
    plt.plot(x, y)
    plt.savefig("images/" + neuron_type + ".png")

def plot_distribution_functions(distribution):
    """
    Load the text file generated in Haskell and use it to
    generate a histogram of the data with 50 bins
    """
    data = np.loadtxt(distribution + ".txt")
    plt.figure()
    plt.hist(data, bins=50)
    plt.savefig("images/" + distribution + ".png")

def main():
    # Iterate through the activation functions and their derivatives
    neuron_types = [
        "sigmoid", "reclu", "tanh",
        "derivative_sigmoid", "derivative_reclu", "derivative_tanh"
    ]

    for activation in neuron_types:
        plot_activation_functions(activation)

    distribution_types = [
        "normal", "uniform"
    ]

    for distribution in distribution_types:
        plot_distribution_functions(distribution)

if __name__ == '__main__':
    main()
